name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/devaneer

            git pull origin main

            # FIX permissions properly (NOT www-data owner)
            sudo chown -R ubuntu:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            # run composer as ubuntu (correct)
            composer install --no-dev --optimize-autoloader

            php artisan migrate --force

            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache